name: Sort Lib Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black flake8
      - name: Lint with black
        run: black --check --diff .
      - name: Lint with flake8
        run: flake8 . --show-source --statistics

  test:
    name: Run Tests
    needs: linting  # Only run tests if linting passes
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.9']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run tests with pytest
        run: pytest

  packaging:
    name: Build and Package
    needs: test  # Only run packaging if tests pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build the package
        run: python -m build
      - name: Upload package
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: python-packages
          path: dist
